apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-app-config
data:
  DB_HOST: db
  DB_PORT: {{ .Values.db.port | quote }}
  DB_NAME: {{ .Values.db.name | quote }}
  DB_USER: {{ .Values.db.user | quote }}
  DB_USE_WINDOWS_AUTH: {{ .Values.env.dbUseWindowsAuth | quote }}
  CORS_ORIGIN: {{ .Values.env.corsOrigin | quote }}
