apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: db
          image: {{ .Values.db.image | quote }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: ACCEPT_EULA
              value: {{ .Values.db.acceptEula | quote }}
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-app-secret
                  key: MSSQL_SA_PASSWORD
