apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-app-config
data:
  DB_HOST: db
  DB_PORT: "1433"
  DB_NAME: ToDoApp
  DB_USER: sa
  DB_USE_WINDOWS_AUTH: "false"
  CORS_ORIGIN: http://localhost:3000
