name: Lab 3 Grading

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create KinD cluster
        uses: helm/kind-action@v1.10.0
        with:
          cluster_name: lab3

      - name: Build app image
        run: docker build -t ecommerce-app:local .

      - name: Load image into KinD
        run: kind load docker-image ecommerce-app:local --name lab3

      - name: Apply manifests
        run: kubectl apply -f k8s/

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh
