name: Lab 4 Grading

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Run Master Validation Script
        run: |
          chmod +x ./tests/lab4_test.sh
          ./tests/lab4_test.sh
